DROP SEQUENCE UPLOAD_SEQ;
DROP SEQUENCE FILE_SEQ;
CREATE SEQUENCE UPLOAD_SEQ;
CREATE SEQUENCE FILE_SEQ;

DROP TABLE FILE_T;
DROP TABLE UPLOAD_T;

CREATE TABLE UPLOAD_T (
  UPLOAD_NO NUMBER NOT NULL,
  UPLOADER  VARCHAR2(100 BYTE),
  IP        VARCHAR2(50 BYTE),
  UPLOAD_DT DATE, 
  CONSTRAINT PK_UPLOAD PRIMARY KEY(UPLOAD_NO)
);
CREATE TABLE FILE_T (
  FILE_NO           NUMBER NOT NULL,
  UPLOAD_PATH       VARCHAR2(500 BYTE),
  ORIGINAL_FILENAME VARCHAR2(300 BYTE),
  FILESYSTEM_NAME   VARCHAR2(40 BYTE),
  UPLOAD_NO         NUMBER,
  CONSTRAINT PK_FILE PRIMARY KEY(FILE_NO),
  CONSTRAINT FK_FILE_UPLOAD FOREIGN KEY(UPLOAD_NO)
    REFERENCES UPLOAD_T(UPLOAD_NO)
      ON DELETE CASCADE
);